version: "3"
services:
  api:
    build: .
    # image: image_name:tag
    links:
      - postgres
    ports:
      - 4000:4000
    volumes:
      - ./:/home/app
      - bundle:/bundle
    stdin_open: true
    tty: true
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ar
      POSTGRES_PASSWORD: ar_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  bundle:

