version: "3"
services:
  portal:
    build: ../doctor-portal-2.0
    # image: image_name:tag
    links:
      - hintmd_db
    env_file: env
    ports:
      - 2000:2000
    volumes:
      - ../doctor-portal-2.0:/usr/src/portal
      - bundle-data:/bundle
    stdin_open: true
    tty: true
  shop:
    build: ../hintmd-solidus
    # image: image_name:tag
    links:
      - hintmd_db
    env_file: env
    ports:
      - 3000:3000
    volumes:
      - ../hintmd-solidus:/usr/src/shop
      - bundle-data:/bundle
    stdin_open: true
    tty: true
  hintmd_db:
    image: postgres:alpine
    env_file: env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data-backup:/docker-entrypoint-initdb.d
volumes:
  db-data:
  bundle-data:
